store_path = "example.db"
# The watch path has to be absolute!
watch_path = "D:\\projects\\htwg\\rust\\auto-stash\\test"
# Debounce time has to be in positive milli seconds
debounce_time = 333
[exclude]
paths = ["test2"]
files = ["test.json"]