store_path = "example.db"
# The watch path has to be absolute! 
# On Windows doubles back slashes are typically used wheres on linux a single slash.
watch_path = "D:\\projects\\htwg\\rust\\auto-stash\\test"
# Debounce time has to be in positive milli seconds!
debounce_time = 333
[exclude]
# Excluded paths have to be relative!
paths = ["test2"]
# Excluded files are recursive!
files = ["test.json"]
