store_path = "demo.db"
# The watch path has to be absolute!
watch_path = "/home/benni/Coding/Demo"
# Debounce time has to be in positive milli seconds
debounce_time = 333
[exclude]
paths = ["test2"]
files = ["test.json"]