[package]
name = "diff"
version = "0.1.0"
authors = ["wolfbiker1 <be631wil@htwg-konstanz.de>", "AlexanderBrese <admin@alexanderbrese.com>"]
edition = "2018"

[dependencies]
serde = "1.0.126"
chrono = "0.4"