[package]
name = "diff"
version = "0.1.0"
authors = ["wolfbiker1 <be631wil@htwg-konstanz.de>", "AlexanderBrese <admin@alexanderbrese.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"

[dev-dependencies]
ctor = "0.1.20"