[package]
name = "event_handle"
version = "0.1.0"
authors = ["wolfbiker1 <be631wil@htwg-konstanz.de>", "AlexanderBrese <admin@alexanderbrese.com>"]
edition = "2018"

[dependencies]
store = { path = "../store" }
diff = { path = "../diff" }
notify = "4.0.12"